//! Library operations that touch both the database and the managed files.
//! Each operation orders its steps so a crash at any point leaves state that
//! `reconcile` can repair.

use std::fs::{self, File};
use std::io::Read;
use std::path::Path;

use crate::catalog;
use crate::db::{books, Database};
use crate::epub;
use crate::error::{AppError, AppResult};
use crate::models::{new_id, Book, BookFormat, BookMetadata, BookStatus, EpubMetadata};
use crate::storage::{self, Storage, COVER_FILE};

/// Copy stage of an import: validates the source, copies it into managed storage and
/// registers the book as `importing`. Metadata and cover are added by `finalize_import`.
pub fn copy_into_library(
    db: &Database,
    storage: &Storage,
    source: &Path,
    on_progress: impl FnMut(u64),
) -> AppResult<Book> {
    if !fs::metadata(source)?.is_file() {
        return Err(AppError::UnsupportedFormat);
    }
    // Checked again on the copy; this only avoids copying a large file that isn't a book.
    storage::detect_format(source)?.ok_or(AppError::UnsupportedFormat)?;
    let title = source
        .file_stem()
        .map(|s| s.to_string_lossy().into_owned())
        .unwrap_or_else(|| "Untitled".into());
    let origin = Origin {
        title: &title,
        catalog_id: None,
    };
    import_stream(db, storage, File::open(source)?, &origin, on_progress)
}

/// Where a book being imported comes from.
pub struct Origin<'a> {
    /// Shown until `finalize_import` reads the book's own metadata.
    pub title: &'a str,
    pub catalog_id: Option<&'a str>,
}

/// Copy stage of an import from any stream (a file or a download). The format is detected on
/// the staged copy, so nothing is trusted before the bytes are on disk.
pub fn import_stream(
    db: &Database,
    storage: &Storage,
    source: impl Read,
    origin: &Origin,
    on_progress: impl FnMut(u64),
) -> AppResult<Book> {
    let id = new_id();
    let staging = storage.staging_dir(&id)?;
    let final_dir = storage.book_dir(&id)?;

    let staged = (|| {
        fs::create_dir_all(&staging)?;
        let incoming = staging.join(storage::INCOMING_FILE);
        let copied = storage::copy_stream(source, &incoming, on_progress)?;
        let format = storage::detect_format(&incoming)?.ok_or(AppError::UnsupportedFormat)?;
        fs::rename(&incoming, staging.join(storage::book_file(format)))?;
        if let Some(existing) = find_duplicate(db, storage, copied.size as i64, &copied.sha256)? {
            return Err(AppError::Duplicate {
                title: existing.title,
                removed: existing.removed_at.is_some(),
            });
        }
        fs::rename(&staging, &final_dir)?;
        Ok::<_, AppError>((copied, format))
    })();
    let (copied, format) = match staged {
        Ok(staged) => staged,
        Err(err) => {
            let _ = storage::remove_dir(&staging);
            return Err(err);
        }
    };

    let new_book = books::NewBook {
        id: &id,
        format,
        title: origin.title,
        file_path: &Storage::book_rel(&id, format),
        file_size: copied.size as i64,
        content_hash: &copied.sha256,
        catalog_id: origin.catalog_id,
    };
    let conn = db.conn();
    if let Err(err) = books::insert_importing(&conn, &new_book) {
        let _ = storage::remove_dir(&final_dir);
        return Err(err);
    }
    books::get(&conn, &id)
}

/// Refuses to download a catalog book that is already in the library (or among removed books).
pub fn ensure_not_downloaded(db: &Database, catalog_id: &str) -> AppResult<()> {
    match books::find_by_catalog_id(&db.conn(), catalog_id)? {
        Some(existing) => Err(AppError::Duplicate {
            title: existing.title,
            removed: existing.removed_at.is_some(),
        }),
        None => Ok(()),
    }
}

/// The book already holding this content, if any. Books imported before hashes existed get
/// theirs computed here, and only when their size matches. A book whose file is missing never
/// counts: importing it again is how the user recovers it.
fn find_duplicate(
    db: &Database,
    storage: &Storage,
    size: i64,
    hash: &str,
) -> AppResult<Option<Book>> {
    let candidates = books::same_size(&db.conn(), size)?;
    for candidate in candidates {
        if candidate.book.status == BookStatus::Missing {
            continue;
        }
        let known = match candidate.content_hash {
            Some(known) => known,
            None => {
                let path = storage.resolve(&candidate.book.file_path);
                let Ok(computed) = storage::hash_file(&path) else {
                    continue;
                };
                books::set_content_hash(&db.conn(), &candidate.book.id, &computed)?;
                computed
            }
        };
        if known == hash {
            return Ok(Some(candidate.book));
        }
    }
    Ok(None)
}

/// Stores the cover generated by the UI. Written atomically next to the PDF.
pub fn save_cover(storage: &Storage, id: &str, bytes: &[u8]) -> AppResult<()> {
    let dir = storage.book_dir(id)?;
    if !dir.is_dir() {
        return Err(AppError::NotFound(format!("book {id}")));
    }
    storage::write_atomic(&dir.join(COVER_FILE), bytes)
}

pub fn finalize_import(
    db: &Database,
    storage: &Storage,
    id: &str,
    meta: &BookMetadata,
) -> AppResult<Book> {
    let book = books::get(&db.conn(), id)?;
    let format = book.format;
    let pages_ok = match format {
        BookFormat::Pdf => meta.page_count >= 1,
        BookFormat::Epub => meta.page_count == 0,
    };
    if !pages_ok {
        return Err(AppError::Invalid("page count".into()));
    }
    // Catalog books keep the catalog's title and author: embedded metadata may use old spellings
    // ("Memorias Posthumas de Braz Cubas") or add subtitles.
    let from_catalog = book
        .catalog_id
        .as_deref()
        .and_then(|c| catalog::get(c).ok());
    let meta = match from_catalog {
        Some(entry) => &BookMetadata {
            title: entry.title.clone(),
            author: Some(entry.author.clone()),
            page_count: meta.page_count,
        },
        None => meta,
    };
    let title = clean_text(&meta.title);
    let meta = BookMetadata {
        title: if title.is_empty() {
            "Untitled".into()
        } else {
            title
        },
        author: meta
            .author
            .as_deref()
            .map(clean_text)
            .filter(|a| !a.is_empty()),
        page_count: meta.page_count,
    };
    let has_cover = storage.book_dir(id)?.join(COVER_FILE).is_file();
    let cover = has_cover.then(|| Storage::cover_rel(id));
    let conn = db.conn();
    books::finalize(&conn, id, &meta, cover.as_deref())?;
    books::get(&conn, id)
}

/// Embedded metadata may carry control characters (e.g. a trailing NUL); drop them and collapse
/// whitespace.
fn clean_text(value: &str) -> String {
    value
        .split(|c: char| c.is_whitespace() || c.is_control())
        .filter(|part| !part.is_empty())
        .collect::<Vec<_>>()
        .join(" ")
}

/// The managed copy of an EPUB book.
fn epub_path(db: &Database, storage: &Storage, id: &str) -> AppResult<std::path::PathBuf> {
    let book = books::get(&db.conn(), id)?;
    if book.format != BookFormat::Epub {
        return Err(AppError::Invalid(format!("book {id} is not an EPUB")));
    }
    Ok(storage.resolve(&book.file_path))
}

/// Title, author and cover presence of an EPUB, read from its package document.
pub fn epub_metadata(db: &Database, storage: &Storage, id: &str) -> AppResult<EpubMetadata> {
    let package = epub::read_package(&epub_path(db, storage, id)?)?;
    Ok(EpubMetadata {
        has_cover: package.has_cover(),
        title: package.title,
        author: package.author,
    })
}

/// The cover image of an EPUB as stored in the book, if any. The UI turns it into `cover.jpg`.
pub fn epub_cover(db: &Database, storage: &Storage, id: &str) -> AppResult<Option<Vec<u8>>> {
    epub::read_cover(&epub_path(db, storage, id)?)
}

/// Undoes an import whose book turned out to be unreadable.
pub fn abort_import(db: &Database, storage: &Storage, id: &str) -> AppResult<()> {
    delete_permanently(db, storage, id)
}

pub fn set_removed(db: &Database, id: &str, removed: bool) -> AppResult<Book> {
    let conn = db.conn();
    books::set_removed(&conn, id, removed)?;
    books::get(&conn, id)
}

/// Deletes the book, its notes and its files. The directory is first moved to a trash
/// location so a crash never leaves a row pointing at a half-deleted directory.
pub fn delete_permanently(db: &Database, storage: &Storage, id: &str) -> AppResult<()> {
    let dir = storage.book_dir(id)?;
    let trash = storage.trash_dir(id)?;
    if dir.exists() {
        fs::rename(&dir, &trash)?;
    }
    if let Err(err) = books::delete(&db.conn(), id) {
        let _ = fs::rename(&trash, &dir);
        return Err(err);
    }
    storage::remove_dir(&trash)
}

#[cfg(test)]
pub(crate) mod tests {
    use super::*;
    use crate::models::BookStatus;

    pub fn setup() -> (tempfile::TempDir, Database, Storage) {
        let dir = tempfile::tempdir().unwrap();
        let storage = Storage::new(dir.path().join("data")).unwrap();
        (dir, Database::open_in_memory().unwrap(), storage)
    }

    pub fn write_pdf(dir: &Path, name: &str) -> std::path::PathBuf {
        let path = dir.join(name);
        // The name goes into the content: identical files would be refused as duplicates.
        fs::write(&path, format!("%PDF-1.7\n% fake body of {name}\n%%EOF")).unwrap();
        path
    }

    #[test]
    fn import_copies_file_and_registers_book() {
        let (dir, db, storage) = setup();
        let source = write_pdf(dir.path(), "Clean Code.pdf");

        let book = copy_into_library(&db, &storage, &source, |_| {}).unwrap();
        assert_eq!(book.status, BookStatus::Importing);
        assert_eq!(book.title, "Clean Code");

        // The managed copy survives the original being deleted.
        fs::remove_file(&source).unwrap();
        assert!(storage.resolve(&book.file_path).is_file());

        save_cover(&storage, &book.id, b"jpeg").unwrap();
        let meta = BookMetadata {
            title: " Clean\u{0}  Code\u{0} ".into(),
            author: Some("\u{0}".into()),
            page_count: 3,
        };
        let book = finalize_import(&db, &storage, &book.id, &meta).unwrap();
        assert_eq!(book.status, BookStatus::Ready);
        assert_eq!(book.title, "Clean Code");
        assert_eq!(book.author, None);
        assert!(book.cover_path.is_some());
        assert_eq!(book.format, BookFormat::Pdf);
        assert!(book.file_path.ends_with("/book.pdf"));
    }

    #[test]
    fn imports_epubs_without_page_counts() {
        let (dir, db, storage) = setup();
        let package = crate::epub::tests::opf(
            "<dc:title>Dune</dc:title><dc:creator>Frank Herbert</dc:creator>",
            r#"<item id="c" href="c.jpg" media-type="image/jpeg" properties="cover-image"/>"#,
        );
        let source = crate::epub::tests::write_epub(
            dir.path(),
            "dune (1).epub",
            &package,
            &[("OEBPS/c.jpg", b"jpeg")],
        );

        let book = copy_into_library(&db, &storage, &source, |_| {}).unwrap();
        assert_eq!(book.format, BookFormat::Epub);
        assert!(book.file_path.ends_with("/book.epub"));
        assert!(storage.resolve(&book.file_path).is_file());

        let meta = epub_metadata(&db, &storage, &book.id).unwrap();
        assert_eq!(meta.title.as_deref(), Some("Dune"));
        assert_eq!(meta.author.as_deref(), Some("Frank Herbert"));
        assert!(meta.has_cover);
        assert_eq!(
            epub_cover(&db, &storage, &book.id).unwrap().as_deref(),
            Some(&b"jpeg"[..])
        );

        let with_pages = |page_count| BookMetadata {
            title: "Dune".into(),
            author: None,
            page_count,
        };
        assert!(matches!(
            finalize_import(&db, &storage, &book.id, &with_pages(10)),
            Err(AppError::Invalid(_))
        ));
        let ready = finalize_import(&db, &storage, &book.id, &with_pages(0)).unwrap();
        assert_eq!(ready.status, BookStatus::Ready);
        assert_eq!(ready.page_count, 0);
    }

    #[test]
    fn epub_reads_reject_pdf_books() {
        let (dir, db, storage) = setup();
        let book =
            copy_into_library(&db, &storage, &write_pdf(dir.path(), "a.pdf"), |_| {}).unwrap();
        assert!(matches!(
            epub_metadata(&db, &storage, &book.id),
            Err(AppError::Invalid(_))
        ));
        let no_pages = BookMetadata {
            title: "a".into(),
            author: None,
            page_count: 0,
        };
        assert!(finalize_import(&db, &storage, &book.id, &no_pages).is_err());
    }

    fn duplicate(result: AppResult<Book>) -> Option<bool> {
        match result {
            Err(AppError::Duplicate { removed, .. }) => Some(removed),
            _ => None,
        }
    }

    #[test]
    fn refuses_the_same_content_twice_without_leftovers() {
        let (dir, db, storage) = setup();
        let source = write_pdf(dir.path(), "a.pdf");
        copy_into_library(&db, &storage, &source, |_| {}).unwrap();

        // Same file, and the same bytes under another name elsewhere.
        let renamed = dir.path().join("copy of a (1).pdf");
        fs::copy(&source, &renamed).unwrap();
        for path in [&source, &renamed] {
            let result = copy_into_library(&db, &storage, path, |_| {});
            assert_eq!(duplicate(result), Some(false), "{path:?}");
        }
        assert_eq!(books::list_all(&db.conn()).unwrap().len(), 1);
        assert_eq!(storage.scan().unwrap().len(), 1, "no staging left behind");
    }

    #[test]
    fn duplicate_error_names_the_book_and_mentions_removed_ones() {
        let (dir, db, storage) = setup();
        let source = write_pdf(dir.path(), "a.pdf");
        let book = copy_into_library(&db, &storage, &source, |_| {}).unwrap();
        set_removed(&db, &book.id, true).unwrap();

        let err = copy_into_library(&db, &storage, &source, |_| {}).unwrap_err();
        assert!(matches!(err, AppError::Duplicate { removed: true, .. }));
        assert!(err
            .to_string()
            .contains("\u{201c}a\u{201d} is already in your library"));
        assert!(err.to_string().contains("restore it"));
    }

    #[test]
    fn hashes_older_books_lazily() {
        let (dir, db, storage) = setup();
        let source = write_pdf(dir.path(), "a.pdf");
        let book = copy_into_library(&db, &storage, &source, |_| {}).unwrap();
        // As if imported before content hashes existed.
        db.conn()
            .execute("UPDATE books SET content_hash = NULL", [])
            .unwrap();

        let result = copy_into_library(&db, &storage, &source, |_| {});
        assert_eq!(duplicate(result), Some(false));
        let hash: Option<String> = db
            .conn()
            .query_row(
                "SELECT content_hash FROM books WHERE id = ?1",
                [&book.id],
                |r| r.get(0),
            )
            .unwrap();
        assert_eq!(hash, Some(storage::hash_file(&source).unwrap()));
    }

    #[test]
    fn allows_same_size_different_content_missing_and_deleted_books() {
        let (dir, db, storage) = setup();
        let a = write_pdf(dir.path(), "a.pdf");
        let b = write_pdf(dir.path(), "b.pdf"); // same length, different bytes
        assert_eq!(
            fs::metadata(&a).unwrap().len(),
            fs::metadata(&b).unwrap().len()
        );
        let book_a = copy_into_library(&db, &storage, &a, |_| {}).unwrap();
        let book_b = copy_into_library(&db, &storage, &b, |_| {}).unwrap();

        // A book whose stored file is gone can be imported again to recover it.
        books::set_status(&db.conn(), &book_a.id, BookStatus::Missing).unwrap();
        copy_into_library(&db, &storage, &a, |_| {}).unwrap();

        // After a permanent delete the book can come back.
        delete_permanently(&db, &storage, &book_b.id).unwrap();
        copy_into_library(&db, &storage, &b, |_| {}).unwrap();
    }

    #[test]
    fn import_rejects_non_pdf_without_leftovers() {
        let (dir, db, storage) = setup();
        let source = dir.path().join("notes.txt");
        fs::write(&source, b"hello").unwrap();

        assert!(matches!(
            copy_into_library(&db, &storage, &source, |_| {}),
            Err(AppError::UnsupportedFormat)
        ));
        assert!(storage.scan().unwrap().is_empty());
        assert!(books::list_all(&db.conn()).unwrap().is_empty());
    }

    #[test]
    fn import_of_missing_file_fails() {
        let (dir, db, storage) = setup();
        let result = copy_into_library(&db, &storage, &dir.path().join("nope.pdf"), |_| {});
        assert!(matches!(result, Err(AppError::NotFound(_))));
    }

    #[cfg(unix)]
    #[test]
    fn import_of_unreadable_file_fails_cleanly() {
        use std::os::unix::fs::PermissionsExt;
        let (dir, db, storage) = setup();
        let source = write_pdf(dir.path(), "locked.pdf");
        fs::set_permissions(&source, fs::Permissions::from_mode(0o000)).unwrap();
        if File::open(&source).is_ok() {
            return; // Running as root: permissions are not enforced.
        }
        let result = copy_into_library(&db, &storage, &source, |_| {});
        assert!(matches!(result, Err(AppError::PermissionDenied(_))));
        assert!(storage.scan().unwrap().is_empty());
        assert!(books::list_all(&db.conn()).unwrap().is_empty());
    }

    fn from_catalog(id: &str) -> Origin<'_> {
        Origin {
            title: "Downloading",
            catalog_id: Some(id),
        }
    }

    #[test]
    fn catalog_imports_keep_the_catalog_title_and_author() {
        let (_dir, db, storage) = setup();
        let bytes = b"%PDF-1.7\n% downloaded\n%%EOF";
        let book = import_stream(
            &db,
            &storage,
            &bytes[..],
            &from_catalog("dom-casmurro"),
            |_| {},
        )
        .unwrap();
        assert_eq!(book.catalog_id.as_deref(), Some("dom-casmurro"));
        assert_eq!(book.title, "Downloading");
        assert_eq!(book.format, BookFormat::Pdf);
        assert!(storage.resolve(&book.file_path).is_file());

        let embedded = BookMetadata {
            title: "Dom Casmurro, by Machado de Assis".into(),
            author: Some("Joaquim Maria Machado de Assis".into()),
            page_count: 2,
        };
        let book = finalize_import(&db, &storage, &book.id, &embedded).unwrap();
        assert_eq!(book.title, "Dom Casmurro");
        assert_eq!(book.author.as_deref(), Some("Machado de Assis"));
        assert_eq!(book.page_count, 2);

        // Already downloaded, even once removed; recovering a missing file is allowed.
        assert!(matches!(
            ensure_not_downloaded(&db, "dom-casmurro"),
            Err(AppError::Duplicate { removed: false, .. })
        ));
        set_removed(&db, &book.id, true).unwrap();
        assert!(matches!(
            ensure_not_downloaded(&db, "dom-casmurro"),
            Err(AppError::Duplicate { removed: true, .. })
        ));
        books::set_status(&db.conn(), &book.id, BookStatus::Missing).unwrap();
        ensure_not_downloaded(&db, "dom-casmurro").unwrap();
        ensure_not_downloaded(&db, "iracema").unwrap();
    }

    /// Yields some bytes, then fails like an interrupted download.
    struct Interrupted(bool);

    impl Read for Interrupted {
        fn read(&mut self, buf: &mut [u8]) -> std::io::Result<usize> {
            if std::mem::replace(&mut self.0, true) {
                return Err(AppError::Network("the download was interrupted".into()).into_io());
            }
            buf[..5].copy_from_slice(b"%PDF-");
            Ok(5)
        }
    }

    #[test]
    fn failed_streams_leave_nothing_behind() {
        let (_dir, db, storage) = setup();
        let origin = from_catalog("iracema");
        let result = import_stream(&db, &storage, Interrupted(false), &origin, |_| {});
        assert!(matches!(result, Err(AppError::Network(_))));
        let result = import_stream(
            &db,
            &storage,
            &b"<html>not a book</html>"[..],
            &origin,
            |_| {},
        );
        assert!(matches!(result, Err(AppError::UnsupportedFormat)));
        assert!(storage.scan().unwrap().is_empty());
        assert!(books::list_all(&db.conn()).unwrap().is_empty());
    }

    /// Downloads every catalog book for real. Network access, so run it by hand:
    /// `cargo test catalog_downloads -- --ignored --nocapture`.
    #[test]
    #[ignore]
    fn catalog_downloads_are_books_of_the_declared_format() {
        let (_dir, db, storage) = setup();
        let mut failures = Vec::new();
        for entry in catalog::entries() {
            let result = crate::download::open(&entry.url).and_then(|download| {
                let origin = from_catalog(&entry.id);
                import_stream(&db, &storage, download.reader, &origin, |_| {})
            });
            match result {
                Ok(book) if book.format == entry.format => {
                    println!("ok   {} ({} KB)", entry.id, book.file_size / 1024)
                }
                Ok(book) => failures.push(format!("{}: got {:?}", entry.id, book.format)),
                Err(err) => failures.push(format!("{}: {err}", entry.id)),
            }
        }
        assert!(failures.is_empty(), "{failures:#?}");
    }

    #[test]
    fn abort_removes_row_and_files() {
        let (dir, db, storage) = setup();
        let book =
            copy_into_library(&db, &storage, &write_pdf(dir.path(), "a.pdf"), |_| {}).unwrap();
        abort_import(&db, &storage, &book.id).unwrap();
        assert!(storage.scan().unwrap().is_empty());
        assert!(books::list_all(&db.conn()).unwrap().is_empty());
    }

    #[test]
    fn soft_remove_keeps_files() {
        let (dir, db, storage) = setup();
        let book =
            copy_into_library(&db, &storage, &write_pdf(dir.path(), "a.pdf"), |_| {}).unwrap();
        let removed = set_removed(&db, &book.id, true).unwrap();
        assert!(removed.removed_at.is_some());
        assert!(storage.resolve(&book.file_path).is_file());
    }

    #[test]
    fn delete_permanently_removes_everything() {
        let (dir, db, storage) = setup();
        let book =
            copy_into_library(&db, &storage, &write_pdf(dir.path(), "a.pdf"), |_| {}).unwrap();
        let note = crate::db::notes::NewNote {
            book_id: &book.id,
            location: "1",
            label: None,
            content: "note",
        };
        crate::db::notes::insert(&db.conn(), &note).unwrap();
        delete_permanently(&db, &storage, &book.id).unwrap();
        assert!(storage.scan().unwrap().is_empty());
        assert!(crate::db::notes::list_by_book(&db.conn(), &book.id)
            .unwrap()
            .is_empty());
    }
}
