//! Library operations that touch both the database and the managed files.
//! Each operation orders its steps so a crash at any point leaves state that
//! `reconcile` can repair.

use std::fs;
use std::path::Path;

use crate::db::{books, Database};
use crate::error::{AppError, AppResult};
use crate::models::{new_id, Book, BookMetadata};
use crate::storage::{self, Storage, BOOK_FILE, COVER_FILE};

/// Copy stage of an import: validates the source, copies it into managed storage and
/// registers the book as `importing`. Metadata and cover are added by `finalize_import`.
pub fn copy_into_library(
    db: &Database,
    storage: &Storage,
    source: &Path,
    on_progress: impl FnMut(u64),
) -> AppResult<Book> {
    let meta = fs::metadata(source)?;
    if !meta.is_file() || !storage::is_pdf(source)? {
        return Err(AppError::NotPdf);
    }

    let id = new_id();
    let staging = storage.staging_dir(&id)?;
    let final_dir = storage.book_dir(&id)?;

    let copied = (|| {
        fs::create_dir_all(&staging)?;
        let size = storage::copy_file(source, &staging.join(BOOK_FILE), on_progress)?;
        fs::rename(&staging, &final_dir)?;
        Ok::<_, AppError>(size)
    })();
    let size = match copied {
        Ok(size) => size,
        Err(err) => {
            let _ = storage::remove_dir(&staging);
            return Err(err);
        }
    };

    let title = source
        .file_stem()
        .map(|s| s.to_string_lossy().into_owned())
        .unwrap_or_else(|| "Untitled".into());
    let new_book = books::NewBook {
        id: &id,
        title: &title,
        file_path: &Storage::book_rel(&id),
        file_size: size as i64,
    };
    let conn = db.conn();
    if let Err(err) = books::insert_importing(&conn, &new_book) {
        let _ = storage::remove_dir(&final_dir);
        return Err(err);
    }
    books::get(&conn, &id)
}

/// Stores the cover generated by the UI. Written atomically next to the PDF.
pub fn save_cover(storage: &Storage, id: &str, bytes: &[u8]) -> AppResult<()> {
    let dir = storage.book_dir(id)?;
    if !dir.is_dir() {
        return Err(AppError::NotFound(format!("book {id}")));
    }
    storage::write_atomic(&dir.join(COVER_FILE), bytes)
}

pub fn finalize_import(
    db: &Database,
    storage: &Storage,
    id: &str,
    meta: &BookMetadata,
) -> AppResult<Book> {
    if meta.page_count < 1 {
        return Err(AppError::Invalid("page count".into()));
    }
    let title = meta.title.trim();
    let meta = BookMetadata {
        title: if title.is_empty() {
            "Untitled".into()
        } else {
            title.to_owned()
        },
        author: meta
            .author
            .as_deref()
            .map(str::trim)
            .filter(|a| !a.is_empty())
            .map(Into::into),
        page_count: meta.page_count,
    };
    let has_cover = storage.book_dir(id)?.join(COVER_FILE).is_file();
    let cover = has_cover.then(|| Storage::cover_rel(id));
    let conn = db.conn();
    books::finalize(&conn, id, &meta, cover.as_deref())?;
    books::get(&conn, id)
}

/// Undoes an import whose PDF turned out to be unreadable.
pub fn abort_import(db: &Database, storage: &Storage, id: &str) -> AppResult<()> {
    delete_permanently(db, storage, id)
}

pub fn set_removed(db: &Database, id: &str, removed: bool) -> AppResult<Book> {
    let conn = db.conn();
    books::set_removed(&conn, id, removed)?;
    books::get(&conn, id)
}

/// Deletes the book, its notes and its files. The directory is first moved to a trash
/// location so a crash never leaves a row pointing at a half-deleted directory.
pub fn delete_permanently(db: &Database, storage: &Storage, id: &str) -> AppResult<()> {
    let dir = storage.book_dir(id)?;
    let trash = storage.trash_dir(id)?;
    if dir.exists() {
        fs::rename(&dir, &trash)?;
    }
    if let Err(err) = books::delete(&db.conn(), id) {
        let _ = fs::rename(&trash, &dir);
        return Err(err);
    }
    storage::remove_dir(&trash)
}

#[cfg(test)]
pub(crate) mod tests {
    use super::*;
    use crate::models::BookStatus;

    pub fn setup() -> (tempfile::TempDir, Database, Storage) {
        let dir = tempfile::tempdir().unwrap();
        let storage = Storage::new(dir.path().join("data")).unwrap();
        (dir, Database::open_in_memory().unwrap(), storage)
    }

    pub fn write_pdf(dir: &Path, name: &str) -> std::path::PathBuf {
        let path = dir.join(name);
        fs::write(&path, b"%PDF-1.7\n% fake body\n%%EOF").unwrap();
        path
    }

    #[test]
    fn import_copies_file_and_registers_book() {
        let (dir, db, storage) = setup();
        let source = write_pdf(dir.path(), "Clean Code.pdf");

        let book = copy_into_library(&db, &storage, &source, |_| {}).unwrap();
        assert_eq!(book.status, BookStatus::Importing);
        assert_eq!(book.title, "Clean Code");

        // The managed copy survives the original being deleted.
        fs::remove_file(&source).unwrap();
        assert!(storage.resolve(&book.file_path).is_file());

        save_cover(&storage, &book.id, b"jpeg").unwrap();
        let meta = BookMetadata {
            title: " Clean Code ".into(),
            author: Some("".into()),
            page_count: 3,
        };
        let book = finalize_import(&db, &storage, &book.id, &meta).unwrap();
        assert_eq!(book.status, BookStatus::Ready);
        assert_eq!(book.title, "Clean Code");
        assert_eq!(book.author, None);
        assert!(book.cover_path.is_some());
    }

    #[test]
    fn import_rejects_non_pdf_without_leftovers() {
        let (dir, db, storage) = setup();
        let source = dir.path().join("notes.txt");
        fs::write(&source, b"hello").unwrap();

        assert!(matches!(
            copy_into_library(&db, &storage, &source, |_| {}),
            Err(AppError::NotPdf)
        ));
        assert!(storage.scan().unwrap().is_empty());
        assert!(books::list_all(&db.conn()).unwrap().is_empty());
    }

    #[test]
    fn import_of_missing_file_fails() {
        let (dir, db, storage) = setup();
        let result = copy_into_library(&db, &storage, &dir.path().join("nope.pdf"), |_| {});
        assert!(matches!(result, Err(AppError::NotFound(_))));
    }

    #[test]
    fn abort_removes_row_and_files() {
        let (dir, db, storage) = setup();
        let book =
            copy_into_library(&db, &storage, &write_pdf(dir.path(), "a.pdf"), |_| {}).unwrap();
        abort_import(&db, &storage, &book.id).unwrap();
        assert!(storage.scan().unwrap().is_empty());
        assert!(books::list_all(&db.conn()).unwrap().is_empty());
    }

    #[test]
    fn soft_remove_keeps_files() {
        let (dir, db, storage) = setup();
        let book =
            copy_into_library(&db, &storage, &write_pdf(dir.path(), "a.pdf"), |_| {}).unwrap();
        let removed = set_removed(&db, &book.id, true).unwrap();
        assert!(removed.removed_at.is_some());
        assert!(storage.resolve(&book.file_path).is_file());
    }

    #[test]
    fn delete_permanently_removes_everything() {
        let (dir, db, storage) = setup();
        let book =
            copy_into_library(&db, &storage, &write_pdf(dir.path(), "a.pdf"), |_| {}).unwrap();
        crate::db::notes::insert(&db.conn(), &book.id, 1, "note").unwrap();
        delete_permanently(&db, &storage, &book.id).unwrap();
        assert!(storage.scan().unwrap().is_empty());
        assert!(crate::db::notes::list_by_book(&db.conn(), &book.id)
            .unwrap()
            .is_empty());
    }
}
