//! Library operations that touch both the database and the managed files.
//! Each operation orders its steps so a crash at any point leaves state that
//! `reconcile` can repair.

use std::fs;
use std::path::Path;

use crate::db::{books, Database};
use crate::epub;
use crate::error::{AppError, AppResult};
use crate::models::{new_id, Book, BookFormat, BookMetadata, EpubMetadata};
use crate::storage::{self, Storage, COVER_FILE};

/// Copy stage of an import: validates the source, copies it into managed storage and
/// registers the book as `importing`. Metadata and cover are added by `finalize_import`.
pub fn copy_into_library(
    db: &Database,
    storage: &Storage,
    source: &Path,
    on_progress: impl FnMut(u64),
) -> AppResult<Book> {
    if !fs::metadata(source)?.is_file() {
        return Err(AppError::UnsupportedFormat);
    }
    let format = storage::detect_format(source)?.ok_or(AppError::UnsupportedFormat)?;

    let id = new_id();
    let staging = storage.staging_dir(&id)?;
    let final_dir = storage.book_dir(&id)?;

    let copied = (|| {
        fs::create_dir_all(&staging)?;
        let target = staging.join(storage::book_file(format));
        let size = storage::copy_file(source, &target, on_progress)?;
        fs::rename(&staging, &final_dir)?;
        Ok::<_, AppError>(size)
    })();
    let size = match copied {
        Ok(size) => size,
        Err(err) => {
            let _ = storage::remove_dir(&staging);
            return Err(err);
        }
    };

    let title = source
        .file_stem()
        .map(|s| s.to_string_lossy().into_owned())
        .unwrap_or_else(|| "Untitled".into());
    let new_book = books::NewBook {
        id: &id,
        format,
        title: &title,
        file_path: &Storage::book_rel(&id, format),
        file_size: size as i64,
    };
    let conn = db.conn();
    if let Err(err) = books::insert_importing(&conn, &new_book) {
        let _ = storage::remove_dir(&final_dir);
        return Err(err);
    }
    books::get(&conn, &id)
}

/// Stores the cover generated by the UI. Written atomically next to the PDF.
pub fn save_cover(storage: &Storage, id: &str, bytes: &[u8]) -> AppResult<()> {
    let dir = storage.book_dir(id)?;
    if !dir.is_dir() {
        return Err(AppError::NotFound(format!("book {id}")));
    }
    storage::write_atomic(&dir.join(COVER_FILE), bytes)
}

pub fn finalize_import(
    db: &Database,
    storage: &Storage,
    id: &str,
    meta: &BookMetadata,
) -> AppResult<Book> {
    let format = books::get(&db.conn(), id)?.format;
    let pages_ok = match format {
        BookFormat::Pdf => meta.page_count >= 1,
        BookFormat::Epub => meta.page_count == 0,
    };
    if !pages_ok {
        return Err(AppError::Invalid("page count".into()));
    }
    let title = clean_text(&meta.title);
    let meta = BookMetadata {
        title: if title.is_empty() {
            "Untitled".into()
        } else {
            title
        },
        author: meta
            .author
            .as_deref()
            .map(clean_text)
            .filter(|a| !a.is_empty()),
        page_count: meta.page_count,
    };
    let has_cover = storage.book_dir(id)?.join(COVER_FILE).is_file();
    let cover = has_cover.then(|| Storage::cover_rel(id));
    let conn = db.conn();
    books::finalize(&conn, id, &meta, cover.as_deref())?;
    books::get(&conn, id)
}

/// Embedded metadata may carry control characters (e.g. a trailing NUL); drop them and collapse
/// whitespace.
fn clean_text(value: &str) -> String {
    value
        .split(|c: char| c.is_whitespace() || c.is_control())
        .filter(|part| !part.is_empty())
        .collect::<Vec<_>>()
        .join(" ")
}

/// The managed copy of an EPUB book.
fn epub_path(db: &Database, storage: &Storage, id: &str) -> AppResult<std::path::PathBuf> {
    let book = books::get(&db.conn(), id)?;
    if book.format != BookFormat::Epub {
        return Err(AppError::Invalid(format!("book {id} is not an EPUB")));
    }
    Ok(storage.resolve(&book.file_path))
}

/// Title, author and cover presence of an EPUB, read from its package document.
pub fn epub_metadata(db: &Database, storage: &Storage, id: &str) -> AppResult<EpubMetadata> {
    let package = epub::read_package(&epub_path(db, storage, id)?)?;
    Ok(EpubMetadata {
        has_cover: package.has_cover(),
        title: package.title,
        author: package.author,
    })
}

/// The cover image of an EPUB as stored in the book, if any. The UI turns it into `cover.jpg`.
pub fn epub_cover(db: &Database, storage: &Storage, id: &str) -> AppResult<Option<Vec<u8>>> {
    epub::read_cover(&epub_path(db, storage, id)?)
}

/// Undoes an import whose book turned out to be unreadable.
pub fn abort_import(db: &Database, storage: &Storage, id: &str) -> AppResult<()> {
    delete_permanently(db, storage, id)
}

pub fn set_removed(db: &Database, id: &str, removed: bool) -> AppResult<Book> {
    let conn = db.conn();
    books::set_removed(&conn, id, removed)?;
    books::get(&conn, id)
}

/// Deletes the book, its notes and its files. The directory is first moved to a trash
/// location so a crash never leaves a row pointing at a half-deleted directory.
pub fn delete_permanently(db: &Database, storage: &Storage, id: &str) -> AppResult<()> {
    let dir = storage.book_dir(id)?;
    let trash = storage.trash_dir(id)?;
    if dir.exists() {
        fs::rename(&dir, &trash)?;
    }
    if let Err(err) = books::delete(&db.conn(), id) {
        let _ = fs::rename(&trash, &dir);
        return Err(err);
    }
    storage::remove_dir(&trash)
}

#[cfg(test)]
pub(crate) mod tests {
    use std::fs::File;

    use super::*;
    use crate::models::BookStatus;

    pub fn setup() -> (tempfile::TempDir, Database, Storage) {
        let dir = tempfile::tempdir().unwrap();
        let storage = Storage::new(dir.path().join("data")).unwrap();
        (dir, Database::open_in_memory().unwrap(), storage)
    }

    pub fn write_pdf(dir: &Path, name: &str) -> std::path::PathBuf {
        let path = dir.join(name);
        fs::write(&path, b"%PDF-1.7\n% fake body\n%%EOF").unwrap();
        path
    }

    #[test]
    fn import_copies_file_and_registers_book() {
        let (dir, db, storage) = setup();
        let source = write_pdf(dir.path(), "Clean Code.pdf");

        let book = copy_into_library(&db, &storage, &source, |_| {}).unwrap();
        assert_eq!(book.status, BookStatus::Importing);
        assert_eq!(book.title, "Clean Code");

        // The managed copy survives the original being deleted.
        fs::remove_file(&source).unwrap();
        assert!(storage.resolve(&book.file_path).is_file());

        save_cover(&storage, &book.id, b"jpeg").unwrap();
        let meta = BookMetadata {
            title: " Clean\u{0}  Code\u{0} ".into(),
            author: Some("\u{0}".into()),
            page_count: 3,
        };
        let book = finalize_import(&db, &storage, &book.id, &meta).unwrap();
        assert_eq!(book.status, BookStatus::Ready);
        assert_eq!(book.title, "Clean Code");
        assert_eq!(book.author, None);
        assert!(book.cover_path.is_some());
        assert_eq!(book.format, BookFormat::Pdf);
        assert!(book.file_path.ends_with("/book.pdf"));
    }

    #[test]
    fn imports_epubs_without_page_counts() {
        let (dir, db, storage) = setup();
        let package = crate::epub::tests::opf(
            "<dc:title>Dune</dc:title><dc:creator>Frank Herbert</dc:creator>",
            r#"<item id="c" href="c.jpg" media-type="image/jpeg" properties="cover-image"/>"#,
        );
        let source = crate::epub::tests::write_epub(
            dir.path(),
            "dune (1).epub",
            &package,
            &[("OEBPS/c.jpg", b"jpeg")],
        );

        let book = copy_into_library(&db, &storage, &source, |_| {}).unwrap();
        assert_eq!(book.format, BookFormat::Epub);
        assert!(book.file_path.ends_with("/book.epub"));
        assert!(storage.resolve(&book.file_path).is_file());

        let meta = epub_metadata(&db, &storage, &book.id).unwrap();
        assert_eq!(meta.title.as_deref(), Some("Dune"));
        assert_eq!(meta.author.as_deref(), Some("Frank Herbert"));
        assert!(meta.has_cover);
        assert_eq!(
            epub_cover(&db, &storage, &book.id).unwrap().as_deref(),
            Some(&b"jpeg"[..])
        );

        let with_pages = |page_count| BookMetadata {
            title: "Dune".into(),
            author: None,
            page_count,
        };
        assert!(matches!(
            finalize_import(&db, &storage, &book.id, &with_pages(10)),
            Err(AppError::Invalid(_))
        ));
        let ready = finalize_import(&db, &storage, &book.id, &with_pages(0)).unwrap();
        assert_eq!(ready.status, BookStatus::Ready);
        assert_eq!(ready.page_count, 0);
    }

    #[test]
    fn epub_reads_reject_pdf_books() {
        let (dir, db, storage) = setup();
        let book =
            copy_into_library(&db, &storage, &write_pdf(dir.path(), "a.pdf"), |_| {}).unwrap();
        assert!(matches!(
            epub_metadata(&db, &storage, &book.id),
            Err(AppError::Invalid(_))
        ));
        let no_pages = BookMetadata {
            title: "a".into(),
            author: None,
            page_count: 0,
        };
        assert!(finalize_import(&db, &storage, &book.id, &no_pages).is_err());
    }

    #[test]
    fn import_rejects_non_pdf_without_leftovers() {
        let (dir, db, storage) = setup();
        let source = dir.path().join("notes.txt");
        fs::write(&source, b"hello").unwrap();

        assert!(matches!(
            copy_into_library(&db, &storage, &source, |_| {}),
            Err(AppError::UnsupportedFormat)
        ));
        assert!(storage.scan().unwrap().is_empty());
        assert!(books::list_all(&db.conn()).unwrap().is_empty());
    }

    #[test]
    fn import_of_missing_file_fails() {
        let (dir, db, storage) = setup();
        let result = copy_into_library(&db, &storage, &dir.path().join("nope.pdf"), |_| {});
        assert!(matches!(result, Err(AppError::NotFound(_))));
    }

    #[cfg(unix)]
    #[test]
    fn import_of_unreadable_file_fails_cleanly() {
        use std::os::unix::fs::PermissionsExt;
        let (dir, db, storage) = setup();
        let source = write_pdf(dir.path(), "locked.pdf");
        fs::set_permissions(&source, fs::Permissions::from_mode(0o000)).unwrap();
        if File::open(&source).is_ok() {
            return; // Running as root: permissions are not enforced.
        }
        let result = copy_into_library(&db, &storage, &source, |_| {});
        assert!(matches!(result, Err(AppError::PermissionDenied(_))));
        assert!(storage.scan().unwrap().is_empty());
        assert!(books::list_all(&db.conn()).unwrap().is_empty());
    }

    #[test]
    fn abort_removes_row_and_files() {
        let (dir, db, storage) = setup();
        let book =
            copy_into_library(&db, &storage, &write_pdf(dir.path(), "a.pdf"), |_| {}).unwrap();
        abort_import(&db, &storage, &book.id).unwrap();
        assert!(storage.scan().unwrap().is_empty());
        assert!(books::list_all(&db.conn()).unwrap().is_empty());
    }

    #[test]
    fn soft_remove_keeps_files() {
        let (dir, db, storage) = setup();
        let book =
            copy_into_library(&db, &storage, &write_pdf(dir.path(), "a.pdf"), |_| {}).unwrap();
        let removed = set_removed(&db, &book.id, true).unwrap();
        assert!(removed.removed_at.is_some());
        assert!(storage.resolve(&book.file_path).is_file());
    }

    #[test]
    fn delete_permanently_removes_everything() {
        let (dir, db, storage) = setup();
        let book =
            copy_into_library(&db, &storage, &write_pdf(dir.path(), "a.pdf"), |_| {}).unwrap();
        let note = crate::db::notes::NewNote {
            book_id: &book.id,
            location: "1",
            label: None,
            content: "note",
        };
        crate::db::notes::insert(&db.conn(), &note).unwrap();
        delete_permanently(&db, &storage, &book.id).unwrap();
        assert!(storage.scan().unwrap().is_empty());
        assert!(crate::db::notes::list_by_book(&db.conn(), &book.id)
            .unwrap()
            .is_empty());
    }
}
